/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CareerResult {
  'improvements' : Array<string>,
  'explanation' : string,
  'careerName' : string,
  'score' : bigint,
  'futureScope' : string,
}
export interface PersonalityAnswer { 'value' : string, 'axis' : string }
export interface Session {
  'id' : SessionId,
  'personality' : Array<PersonalityAnswer>,
  'title' : string,
  'interests' : Array<string>,
  'preview' : string,
  'results' : Array<CareerResult>,
  'timestamp' : bigint,
  'skills' : Array<SkillRating>,
}
export interface SessionData {
  'personality' : Array<PersonalityAnswer>,
  'title' : string,
  'interests' : Array<string>,
  'preview' : string,
  'results' : Array<CareerResult>,
  'timestamp' : bigint,
  'skills' : Array<SkillRating>,
}
export type SessionId = bigint;
export interface SessionSummary {
  'id' : SessionId,
  'title' : string,
  'preview' : string,
  'timestamp' : bigint,
}
export interface SkillRating { 'name' : string, 'rating' : bigint }
export interface _SERVICE {
  'createSession' : ActorMethod<[], SessionId>,
  'deleteSession' : ActorMethod<[SessionId], boolean>,
  'getSession' : ActorMethod<[SessionId], [] | [Session]>,
  'listSessions' : ActorMethod<[], Array<SessionSummary>>,
  'saveSession' : ActorMethod<[SessionId, SessionData], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];