/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const SessionId = IDL.Nat;
export const PersonalityAnswer = IDL.Record({
  'value' : IDL.Text,
  'axis' : IDL.Text,
});
export const CareerResult = IDL.Record({
  'improvements' : IDL.Vec(IDL.Text),
  'explanation' : IDL.Text,
  'careerName' : IDL.Text,
  'score' : IDL.Nat,
  'futureScope' : IDL.Text,
});
export const SkillRating = IDL.Record({
  'name' : IDL.Text,
  'rating' : IDL.Nat,
});
export const Session = IDL.Record({
  'id' : SessionId,
  'personality' : IDL.Vec(PersonalityAnswer),
  'title' : IDL.Text,
  'interests' : IDL.Vec(IDL.Text),
  'preview' : IDL.Text,
  'results' : IDL.Vec(CareerResult),
  'timestamp' : IDL.Int,
  'skills' : IDL.Vec(SkillRating),
});
export const SessionSummary = IDL.Record({
  'id' : SessionId,
  'title' : IDL.Text,
  'preview' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const SessionData = IDL.Record({
  'personality' : IDL.Vec(PersonalityAnswer),
  'title' : IDL.Text,
  'interests' : IDL.Vec(IDL.Text),
  'preview' : IDL.Text,
  'results' : IDL.Vec(CareerResult),
  'timestamp' : IDL.Int,
  'skills' : IDL.Vec(SkillRating),
});

export const idlService = IDL.Service({
  'createSession' : IDL.Func([], [SessionId], []),
  'deleteSession' : IDL.Func([SessionId], [IDL.Bool], []),
  'getSession' : IDL.Func([SessionId], [IDL.Opt(Session)], ['query']),
  'listSessions' : IDL.Func([], [IDL.Vec(SessionSummary)], ['query']),
  'saveSession' : IDL.Func([SessionId, SessionData], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const SessionId = IDL.Nat;
  const PersonalityAnswer = IDL.Record({
    'value' : IDL.Text,
    'axis' : IDL.Text,
  });
  const CareerResult = IDL.Record({
    'improvements' : IDL.Vec(IDL.Text),
    'explanation' : IDL.Text,
    'careerName' : IDL.Text,
    'score' : IDL.Nat,
    'futureScope' : IDL.Text,
  });
  const SkillRating = IDL.Record({ 'name' : IDL.Text, 'rating' : IDL.Nat });
  const Session = IDL.Record({
    'id' : SessionId,
    'personality' : IDL.Vec(PersonalityAnswer),
    'title' : IDL.Text,
    'interests' : IDL.Vec(IDL.Text),
    'preview' : IDL.Text,
    'results' : IDL.Vec(CareerResult),
    'timestamp' : IDL.Int,
    'skills' : IDL.Vec(SkillRating),
  });
  const SessionSummary = IDL.Record({
    'id' : SessionId,
    'title' : IDL.Text,
    'preview' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const SessionData = IDL.Record({
    'personality' : IDL.Vec(PersonalityAnswer),
    'title' : IDL.Text,
    'interests' : IDL.Vec(IDL.Text),
    'preview' : IDL.Text,
    'results' : IDL.Vec(CareerResult),
    'timestamp' : IDL.Int,
    'skills' : IDL.Vec(SkillRating),
  });
  
  return IDL.Service({
    'createSession' : IDL.Func([], [SessionId], []),
    'deleteSession' : IDL.Func([SessionId], [IDL.Bool], []),
    'getSession' : IDL.Func([SessionId], [IDL.Opt(Session)], ['query']),
    'listSessions' : IDL.Func([], [IDL.Vec(SessionSummary)], ['query']),
    'saveSession' : IDL.Func([SessionId, SessionData], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };